import { ThemeVibe } from '../types';

export interface ThemeColors {
  bg: string;
  surface: string;
  surfaceHover: string;
  border: string;
  textPrimary: string;
  textSecondary: string;
  textMuted: string;
  accent: string;
  accentHover: string;
  accentText: string;
  badgeBg: string;
  badgeText: string;
  cardBg: string;
}

export const themeMap: Record<ThemeVibe, ThemeColors> = {
  'modern-minimal': {
    bg: 'bg-slate-50',
    surface: 'bg-white',
    surfaceHover: 'hover:bg-slate-50',
    border: 'border-slate-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-700',
    textMuted: 'text-slate-500',
    accent: 'bg-indigo-600',
    accentHover: 'hover:bg-indigo-700',
    accentText: 'text-indigo-600',
    badgeBg: 'bg-indigo-50',
    badgeText: 'text-indigo-700',
    cardBg: 'bg-white',
  },
  'editorial-warm': {
    bg: 'bg-[#faf8f5]',
    surface: 'bg-[#ffffff]',
    surfaceHover: 'hover:bg-[#f5f1ea]',
    border: 'border-[#e7e1d7]',
    textPrimary: 'text-[#201c18]',
    textSecondary: 'text-[#484138]',
    textMuted: 'text-[#7e7467]',
    accent: 'bg-[#9a5b32]',
    accentHover: 'hover:bg-[#834c28]',
    accentText: 'text-[#9a5b32]',
    badgeBg: 'bg-[#f4eae1]',
    badgeText: 'text-[#8b4d24]',
    cardBg: 'bg-[#ffffff]',
  },
  'dark-obsidian': {
    bg: 'bg-[#0b0d11]',
    surface: 'bg-[#13171f]',
    surfaceHover: 'hover:bg-[#1a202c]',
    border: 'border-zinc-800',
    textPrimary: 'text-zinc-100',
    textSecondary: 'text-zinc-300',
    textMuted: 'text-zinc-400',
    accent: 'bg-emerald-500',
    accentHover: 'hover:bg-emerald-400',
    accentText: 'text-emerald-400',
    badgeBg: 'bg-emerald-950/60',
    badgeText: 'text-emerald-300',
    cardBg: 'bg-[#13171f]',
  },
  'bold-creative': {
    bg: 'bg-[#f4f7fb]',
    surface: 'bg-white',
    surfaceHover: 'hover:bg-blue-50/50',
    border: 'border-blue-100',
    textPrimary: 'text-slate-950',
    textSecondary: 'text-slate-700',
    textMuted: 'text-slate-500',
    accent: 'bg-blue-600',
    accentHover: 'hover:bg-blue-700',
    accentText: 'text-blue-600',
    badgeBg: 'bg-blue-50',
    badgeText: 'text-blue-700',
    cardBg: 'bg-white',
  },
  'cyber-neon': {
    bg: 'bg-[#090b16]',
    surface: 'bg-[#101426]',
    surfaceHover: 'hover:bg-[#161c36]',
    border: 'border-cyan-950/80',
    textPrimary: 'text-cyan-50',
    textSecondary: 'text-cyan-200/80',
    textMuted: 'text-cyan-400/50',
    accent: 'bg-cyan-500',
    accentHover: 'hover:bg-cyan-400',
    accentText: 'text-cyan-400',
    badgeBg: 'bg-cyan-950/70',
    badgeText: 'text-cyan-300',
    cardBg: 'bg-[#101426]',
  },
  'midnight-amethyst': {
    bg: 'bg-[#0a0714]',
    surface: 'bg-[#130f24]',
    surfaceHover: 'hover:bg-[#1c1636]',
    border: 'border-purple-950/80',
    textPrimary: 'text-purple-50',
    textSecondary: 'text-purple-200/80',
    textMuted: 'text-purple-400/50',
    accent: 'bg-purple-600',
    accentHover: 'hover:bg-purple-500',
    accentText: 'text-purple-400',
    badgeBg: 'bg-purple-950/70',
    badgeText: 'text-purple-300',
    cardBg: 'bg-[#130f24]',
  },
  'crimson-noir': {
    bg: 'bg-[#0f0c0e]',
    surface: 'bg-[#181216]',
    surfaceHover: 'hover:bg-[#231a20]',
    border: 'border-rose-950/80',
    textPrimary: 'text-rose-50',
    textSecondary: 'text-rose-200/80',
    textMuted: 'text-rose-400/50',
    accent: 'bg-rose-600',
    accentHover: 'hover:bg-rose-500',
    accentText: 'text-rose-400',
    badgeBg: 'bg-rose-950/70',
    badgeText: 'text-rose-300',
    cardBg: 'bg-[#181216]',
  },
  'solar-amber': {
    bg: 'bg-[#0d0f14]',
    surface: 'bg-[#151a24]',
    surfaceHover: 'hover:bg-[#1d2433]',
    border: 'border-amber-950/80',
    textPrimary: 'text-amber-50',
    textSecondary: 'text-amber-200/80',
    textMuted: 'text-amber-400/50',
    accent: 'bg-amber-500',
    accentHover: 'hover:bg-amber-400',
    accentText: 'text-amber-400',
    badgeBg: 'bg-amber-950/70',
    badgeText: 'text-amber-300',
    cardBg: 'bg-[#151a24]',
  },
  'nordic-frost': {
    bg: 'bg-[#f0f9ff]',
    surface: 'bg-white',
    surfaceHover: 'hover:bg-sky-50',
    border: 'border-sky-200',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-700',
    textMuted: 'text-sky-600/70',
    accent: 'bg-sky-600',
    accentHover: 'hover:bg-sky-700',
    accentText: 'text-sky-600',
    badgeBg: 'bg-sky-100',
    badgeText: 'text-sky-800',
    cardBg: 'bg-white',
  },
  'forest-matrix': {
    bg: 'bg-[#06110a]',
    surface: 'bg-[#0e1d13]',
    surfaceHover: 'hover:bg-[#14281b]',
    border: 'border-emerald-950/80',
    textPrimary: 'text-emerald-50',
    textSecondary: 'text-emerald-200/80',
    textMuted: 'text-emerald-400/50',
    accent: 'bg-emerald-500',
    accentHover: 'hover:bg-emerald-400',
    accentText: 'text-emerald-400',
    badgeBg: 'bg-emerald-950/70',
    badgeText: 'text-emerald-300',
    cardBg: 'bg-[#0e1d13]',
  },
};
